/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Antonio
 */
public class FormInicio extends javax.swing.JFrame {

    /**
     * Creates new form FormInicio
     */
    public FormInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        ImageIcon icon = new ImageIcon(getClass().getResource("/assets/inicio_background.jpg"));
        Image image = icon.getImage();
        jdpContenedor = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCompletos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRol = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPendientes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRegistro = new javax.swing.JMenu();
        jmFormCliente = new javax.swing.JMenuItem();
        jmFormLibro = new javax.swing.JMenuItem();
        jmFormAutor = new javax.swing.JMenuItem();
        jmNegocio = new javax.swing.JMenu();
        jmFormVenta = new javax.swing.JMenuItem();
        jmFormPrestamo = new javax.swing.JMenuItem();
        jmListar = new javax.swing.JMenu();
        jmMostrarVentas = new javax.swing.JMenuItem();
        jmMostrarPrestamos = new javax.swing.JMenuItem();
        jmMostrarLibros = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jdpContenedorLayout = new javax.swing.GroupLayout(jdpContenedor);
        jdpContenedor.setLayout(jdpContenedorLayout);
        jdpContenedorLayout.setHorizontalGroup(
            jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        jdpContenedorLayout.setVerticalGroup(
            jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 91, 104));
        jLabel1.setText("Usuario");

        txtNombreCompletos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        txtNombreCompletos.setText("Isaias Antonio Mayhuay");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 91, 104));
        jLabel2.setText("Nombres");

        txtusuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        txtusuario.setText("Antonio");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 91, 104));
        jLabel3.setText("Rol");

        txtRol.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        txtRol.setText("Ventas");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo_v2_biblioteca.PNG"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/usuario_image.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNombreCompletos, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCompletos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        btnPendientes.setBackground(new java.awt.Color(0, 91, 104));
        btnPendientes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnPendientes.setForeground(new java.awt.Color(255, 255, 255));
        btnPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cerrar_sesion_iocn.png"))); // NOI18N
        btnPendientes.setText("Cerrar Sesión");
        btnPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnPendientes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBorder(null);

        jmRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/registros_icon.png"))); // NOI18N
        jmRegistro.setText("Registro");
        jmRegistro.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jmRegistro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jmRegistro.setIconTextGap(10);
        jmRegistro.setMargin(new java.awt.Insets(3, 20, 3, 6));

        jmFormCliente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jmFormCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/clientes_icon.png"))); // NOI18N
        jmFormCliente.setText("Cliente");
        jmRegistro.add(jmFormCliente);

        jmFormLibro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jmFormLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/libros_icon.png"))); // NOI18N
        jmFormLibro.setText("Libro");
        jmRegistro.add(jmFormLibro);

        jmFormAutor.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jmFormAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/autores_icon.png"))); // NOI18N
        jmFormAutor.setText("Autor");
        jmRegistro.add(jmFormAutor);

        jMenuBar1.add(jmRegistro);

        jmNegocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/negocio_icon.png"))); // NOI18N
        jmNegocio.setText("Negocio");
        jmNegocio.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jmNegocio.setIconTextGap(10);
        jmNegocio.setMargin(new java.awt.Insets(3, 20, 3, 6));

        jmFormVenta.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jmFormVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/vender_libro_icon.png"))); // NOI18N
        jmFormVenta.setText("Venta");
        jmNegocio.add(jmFormVenta);

        jmFormPrestamo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jmFormPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/prestamo_libro_icon.png"))); // NOI18N
        jmFormPrestamo.setText("Prestamo");
        jmNegocio.add(jmFormPrestamo);

        jMenuBar1.add(jmNegocio);

        jmListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/listar_icon.png"))); // NOI18N
        jmListar.setText("Listar");
        jmListar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jmListar.setIconTextGap(10);
        jmListar.setMargin(new java.awt.Insets(3, 20, 3, 6));

        jmMostrarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ListarVentas_icon.png"))); // NOI18N
        jmMostrarVentas.setText("Mostrar Ventas");
        jmListar.add(jmMostrarVentas);

        jmMostrarPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/listPrest_icon.png"))); // NOI18N
        jmMostrarPrestamos.setText("Mostrar prestamos");
        jmListar.add(jmMostrarPrestamos);

        jmMostrarLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ListarLibros_icon.png"))); // NOI18N
        jmMostrarLibros.setText("Mostrar Libros");
        jmListar.add(jmMostrarLibros);

        jMenuBar1.add(jmListar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpContenedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jdpContenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPendientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPendientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JDesktopPane jdpContenedor;
    public javax.swing.JMenuItem jmFormAutor;
    public javax.swing.JMenuItem jmFormCliente;
    public javax.swing.JMenuItem jmFormLibro;
    public javax.swing.JMenuItem jmFormPrestamo;
    public javax.swing.JMenuItem jmFormVenta;
    private javax.swing.JMenu jmListar;
    public javax.swing.JMenuItem jmMostrarLibros;
    public javax.swing.JMenuItem jmMostrarPrestamos;
    public javax.swing.JMenuItem jmMostrarVentas;
    private javax.swing.JMenu jmNegocio;
    private javax.swing.JMenu jmRegistro;
    public javax.swing.JLabel txtNombreCompletos;
    public javax.swing.JLabel txtRol;
    public javax.swing.JLabel txtusuario;
    // End of variables declaration//GEN-END:variables
}
